name: DirTesting

on:  
  push:
    branches:
      - 'master'

  workflow_dispatch:  

jobs:
 
  build:
    runs-on: ubuntu-latest
   
    steps:      
      - uses: actions/checkout@v4 
    
      - name: Run a multi-line script
        run: |
          if [ ! -d "${{github.workflow}}" ]; then             
            mkdir ${{github.workflow}}                         
          fi  
          mkdir -p ${{github.workflow}}/${{ github.run_number }} 
