name: DirTesting

on:  
  push:
    branches:
      - 'master'

  workflow_dispatch:  

jobs:
 
  build:
    runs-on: ubuntu-latest
   
    steps:      
      - uses: actions/checkout@v4 
    
      - name: Run a multi-line script
        run: |
          if [ ! -d "${{github.workflow}}" ]; then             
            mkdir ${{github.workflow}}                         
          fi  
          mkdir -p ${{github.workflow}}/${{ github.run_number }} 

      - name: Deploy report to Github Pages   
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: master
          publish_dir: ./${{github.workflow}}   
