name: DirTesting

on:  
  push:
    branches:
      - 'master'

  workflow_dispatch:  

jobs:
 
  build:
    runs-on: ubuntu-latest
   
    steps:      
      - uses: actions/checkout@v4 
    
      - name: Run a multi-line script
        run: |
          if [ ! -d "${{github.workflow}}" ]; then             
            mkdir ${{github.workflow}}                         
          fi  
          mkdir -p ${{github.workflow}}/${{ github.run_number }} 

          ls

          cd ${{github.workflow}}

          ls

          # git config --global user.name "GitHub Actions"
          # git config --global user.email "actions@github.com"
          # git fetch origin master   
          # git stash 
          # git checkout master          
          # git add .
          # git commit -m "Workflow-Testing_${{github.run_number}}"  
          # git push origin master  
