name: DirTesting

on:  
  push:
    branches:
      - 'master'

  workflow_dispatch:  

jobs:
 
  build:
    runs-on: ubuntu-latest
   
    steps:      
      - uses: actions/checkout@v4 
    
      - name: Run script
        run: |
          ls
          cd ${{github.workflow}}
          ls
          cd ..
          echo "----------------------------------------------------------------------"
          max=20
          dir_count=$(find ${{github.workflow}} -mindepth 1 -maxdepth 1 -type d | wc -l)

          if [ "$dir_count" -gt "$max" ]; then
            # Find the directory with the smallest numeric name
            oldest_dir=$(find ${{github.workflow}} -mindepth 1 -maxdepth 1 -type d -printf '%f\n' | sort -n | head -n 1)
            echo "Deleting the oldest directory: $oldest_dir"
            rm -rf "${{github.workflow}}/$oldest_dir"
            cd ${{github.workflow}}
            ls
          else
            echo "There are $max or fewer directories. No deletion necessary."
          fi
